import { Instrument } from '@/types';

export const seedInstruments: Omit<Instrument, 'id' | 'position' | 'metadata'>[] = [
  {
    name: 'BBC Symphony Orchestra',
    developer: 'Spitfire Audio',
    host: 'Kontakt',
    category: 'Orchestral',
    tags: ['GO-TO'],
    notes: 'Full orchestral library with excellent strings, brass, and woodwinds',
    pairings: [],
    color: '#3b82f6',
  },
  {
    name: 'Pigments',
    developer: 'Arturia',
    host: 'Standalone',
    category: 'Synth',
    tags: ['GO-TO'],
    notes: 'Versatile synthesizer with dual engines',
    pairings: [],
    color: '#8b5cf6',
  },
  {
    name: 'RA Lofi Traveller',
    developer: 'Rigid Audio',
    host: 'VST3',
    category: 'Synth',
    tags: ['Hidden Gem'],
    notes: 'Great for degraded ambient pads',
    pairings: [],
    color: '#8b5cf6',
  },
  {
    name: 'Time Textures Expanded',
    developer: 'Native Instruments',
    host: 'Kontakt',
    category: 'Effects',
    tags: ['Specialty'],
    notes: 'Layer under orchestral for sci-fi atmosphere',
    pairings: [],
    color: '#10b981',
  },
  {
    name: 'Keyscape',
    developer: 'Spectrasonics',
    host: 'Standalone',
    category: 'Keys',
    tags: ['GO-TO'],
    notes: 'Comprehensive keyboard collection',
    pairings: [],
    color: '#f59e0b',
  },
  {
    name: 'Superior Drummer 3',
    developer: 'Toontrack',
    host: 'Standalone',
    category: 'Drums',
    tags: ['GO-TO'],
    notes: 'Professional drum library',
    pairings: [],
    color: '#ef4444',
  },
  {
    name: 'Omnisphere',
    developer: 'Spectrasonics',
    host: 'Standalone',
    category: 'Synth',
    tags: ['GO-TO'],
    notes: 'Powerful synthesizer with extensive sound library',
    pairings: [],
    color: '#8b5cf6',
  },
  {
    name: 'Spitfire Studio Strings',
    developer: 'Spitfire Audio',
    host: 'Kontakt',
    category: 'Orchestral',
    tags: [],
    notes: 'Clean studio string recordings',
    pairings: [],
    color: '#3b82f6',
  },
  {
    name: 'Massive X',
    developer: 'Native Instruments',
    host: 'Standalone',
    category: 'Synth',
    tags: [],
    notes: 'Modern wavetable synthesizer',
    pairings: [],
    color: '#8b5cf6',
  },
  {
    name: 'Cinematic Percussion',
    developer: '8Dio',
    host: 'Kontakt',
    category: 'Drums',
    tags: ['Cinematic'],
    notes: 'Epic cinematic percussion',
    pairings: [],
    color: '#ef4444',
  },
];
